project:
  type: website

website:
  title: "Farrukh Nauman"
  navbar: 
    title: false # "Farrukh Nauman"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd 
        text: Projects
      - href: posts.qmd 
        text: Blog
      - href: randomposts.qmd
        text: TIL/Random

    right:
      - icon: github
        href: https://github.com/fnauman
      - icon: twitter
        href: https://twitter.com/naumanf_
      - icon: linkedin
        href: https://www.linkedin.com/in/fnauman/
      - icon: envelope
        aria-label: email
        href: "mailto:farrukh.nauman@ri.se"  
  
  google-analytics: G-9BN5NTZ1J1
  open-graph: true
  twitter-card: 
    creator: "@naumanf_" 
    site: "@naumanf_"

format:
  html:
    theme: 
      light: flatly # styles.scss # [flatly, styles.scss]
      dark: darkly
    # css: styles.css
    toc: true # false
    page-layout: full
