project:
  type: website

website:
  title: "Farrukh Nauman"
  site-url: https://fnauman.com
  description: "Machine Learning Consulting, AI Research, and Technical Blog"
  navbar: 
    title: false # "Farrukh Nauman"
    left:
      - href: index.qmd
        text: Home
      - href: consulting.qmd 
        text: Consulting
      - href: posts.qmd 
        text: Blog
      - href: cv.qmd
        text: CV
      # - href: randomposts.qmd
      #   text: TIL/Random

    right:
      - icon: github
        href: https://github.com/fnauman
      - icon: x
        href: https://x.com/fnauman
      - icon: linkedin
        href: https://www.linkedin.com/in/fnauman/
      - icon: envelope
        aria-label: email
        href: "mailto:farrukh.nauman@inertialrange.com"  
  
  page-footer:
    left: "Copyright 2026, Farrukh Nauman"
    right: 
      - icon: github
        href: https://github.com/fnauman
      - icon: x
        href: https://x.com/fnauman
      - icon: linkedin
        href: https://www.linkedin.com/in/fnauman/
      - icon: envelope
        aria-label: email
        href: "mailto:farrukh.nauman@inertialrange.com"  
  
  google-analytics: G-9BN5NTZ1J1
  open-graph: true
  twitter-card: 
    creator: "@fnauman" 
    site: "@fnauman"

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
